# iproute2 - patched for EVPN Multihome protocol field support

IPROUTE2_VERSION_BASE = 6.15.0
IPROUTE2_VERSION = $(IPROUTE2_VERSION_BASE)-1
IPROUTE2_VERSION_SONIC = $(IPROUTE2_VERSION_BASE)-1sonic1

export IPROUTE2_VERSION_BASE
export IPROUTE2_VERSION
export IPROUTE2_VERSION_SONIC

IPROUTE2 = iproute2_$(IPROUTE2_VERSION_SONIC)_$(CONFIGURED_ARCH).deb
$(IPROUTE2)_SRC_PATH = $(SRC_PATH)/iproute2
SONIC_MAKE_DEBS += $(IPROUTE2)

IPROUTE2_DBG = iproute2-dbgsym_$(IPROUTE2_VERSION_SONIC)_$(CONFIGURED_ARCH).deb
$(IPROUTE2_DBG)_DEPENDS += $(IPROUTE2)
$(IPROUTE2_DBG)_RDEPENDS += $(IPROUTE2)
$(eval $(call add_derived_package,$(IPROUTE2),$(IPROUTE2_DBG)))
